[project]
name = "googleform-autofill-and-submit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ntplib>=0.4.0",
    "requests>=2.32.5",
]
